#
# References: 
# 1. https://gist.github.com/brunosimioni/2bcbb91edd4fbaeb8cccbbf490c5685c
#
version: '3.0'

services:

  #
  # Grafana comes with Prometheus Data Source built in. Nothing to add. 
  #
  grafana:
    image: grafana/grafana:6.3.2
    container_name: grafana
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./grafana/config.ini:/var/lib/grafana/config.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_INSTALL_PLUGINS=flant-statusmap-panel
    ports:
      - "5000:3000"

  pushgateway:
    image: prom/pushgateway:v0.9.1
    container_name: pushgateway
    ports:
      - "9091:9091"

  prometheus:
    image: prom/prometheus:v2.11.1
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=200h'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"      
