# References:
# 1. provisioning/datasources/all.yml
#    https://github.com/cirocosta/sample-grafana/blob/master/grafana/provisioning/datasources/all.yml\
# 2. https://56k.cloud/blog/provisioning-grafana-datasources-and-dashboards-automagically/
apiVersion: 1

datasources:
-  access: 'proxy'                       # make grafana perform the requests
   name: 'Prometheus'                    # name of the datasource
   editable: true                        # whether it should be editable
   is_default: true                      # whether this should be the default DS
   org_id: 1                             # id of the organization to tie this datasource to
   type: 'prometheus'                    # type of the data source
   url: 'http://prometheus:9090'         # url of the prom instance
   version: 1                            # well, versioning
   